// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg1RvCi__eBUYmoboh1rk2A9l-9Rjidt0',
    appId: '1:555286530543:web:48ea1feb4cd87baa3b4e1a',
    messagingSenderId: '555286530543',
    projectId: 'nti-project-811dc',
    authDomain: 'nti-project-811dc.firebaseapp.com',
    storageBucket: 'nti-project-811dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFg3zIO_wmrP325_gq7OzQem42BKsvtgc',
    appId: '1:555286530543:android:5f795905a8d8e0373b4e1a',
    messagingSenderId: '555286530543',
    projectId: 'nti-project-811dc',
    storageBucket: 'nti-project-811dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4W5ImWjDyTmVHHSgikS2hbs8cytQ3Yxk',
    appId: '1:555286530543:ios:88e4391efae72a2d3b4e1a',
    messagingSenderId: '555286530543',
    projectId: 'nti-project-811dc',
    storageBucket: 'nti-project-811dc.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4W5ImWjDyTmVHHSgikS2hbs8cytQ3Yxk',
    appId: '1:555286530543:ios:88e4391efae72a2d3b4e1a',
    messagingSenderId: '555286530543',
    projectId: 'nti-project-811dc',
    storageBucket: 'nti-project-811dc.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg1RvCi__eBUYmoboh1rk2A9l-9Rjidt0',
    appId: '1:555286530543:web:51bbe74297ad5d713b4e1a',
    messagingSenderId: '555286530543',
    projectId: 'nti-project-811dc',
    authDomain: 'nti-project-811dc.firebaseapp.com',
    storageBucket: 'nti-project-811dc.firebasestorage.app',
  );
}
